description: # Info dump -- description params are not loaded
  text: 'very first model run!'

global:
  seed: 0
  mode: finetuning          #pretrain | finetuning
  train_head_only_model: true
  train_full_model: true
  efficient_net_version: efficientnet-b3
  load_from_pretrained: false  # Pretrained weights from 2018 petfinder dataset
  pretrained_model_location:
  folder_suffix: first_model   # cant use '-' in folder names
  #cross_validation: True | False
  num_folds: 5
# TRAIN AUGMENTATION LIST ?

head_only_model:
  name:

  epochs: 6
  batch_size: 64

  evaluate_per: epoch   # only epoch is possible atm
  evaluate_interval: 1  # can take only fractions or 1 | value < 1

  learning_rate: 0.1
  learning_rate_drop_every: 2
  learning_rate_drop_factor: 0.1


full_model:
  name: pawpularity-full-model

  epochs: 6
  batch_size: 64

  evaluate_per: epoch    # only epoch is possible atm
  evaluate_interval: 1   # can take fractions

  learning_rate: 0.001
  learning_rate_drop_every: 3
  learning_rate_drop_factor: 0.33
