description: # Info dump -- description params are not loaded
  text: 'very first model run!'

global:
  folder_suffix: pt_ft_1   # cant use '-' in folder names
  mode: finetuning          #pretraining | finetuning
  load_from_pretrained: true  # Pretrained weights from 2018 petfinder dataset
  pretrained_model_location: 20211125-pretrained_effnetb3
  train_head_only_model: true
  train_full_model: true
  efficient_net_version: efficientnet-b3
  drive_save_path: "/content/drive/MyDrive/petfinder"
  save_to_drive: true
  num_folds: 5
  seed: 0
  #cross_validation: true #| by default pretraining is set to validation set

head_only_model:
  name:

  epochs: 6
  batch_size: 64

  evaluate_per: epoch   # only epoch is possible atm
  evaluate_interval: 1  # can take only fractions or 1 | value < 1

  learning_rate: 0.1
  learning_rate_drop_every: 2
  learning_rate_drop_factor: 0.1


full_model:
  name: pawpularity-full-model

  epochs: 6
  batch_size: 64

  evaluate_per: epoch    # only epoch is possible atm
  evaluate_interval: 1   # can take fractions

  learning_rate: 0.001
  learning_rate_drop_every: 2
  learning_rate_drop_factor: 0.1
